name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install dependencies
      run: npm install
    - name: NPM build
      run: npm run build --if-present
    - name: Git config auto deploy
      run: | 
        git config --local user.email "lucas.avelino1203@gmail.com"
        git checkout -b gh-pages
        git commit -m "Publish" -a
    - name: Push changes
      uses: LucasAvelino0509/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB }}
